services:
  spotdl-frontend:
    build:
      context: .
    ports:
      - "5173:5173"  # Frontend
    user: 1000:1000
    volumes:
      - ./downloads:/downloads  # Mount downloads directory
      - /home/tanc/mnt/media/music:/music  # Mount music directory
      - ./config:/app/backend/config  # Mount config directory
    environment:
      - NODE_ENV=development # Set NODE_ENV to development if needed
      - VITE_API_URL=http://localhost:3001  # Backend API URL
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./public
          target: /app/public
          action: sync
        - path: ./backend
          target: /app/backend
          action: sync
        - path: ./package.json
          action: rebuild
        - path: ./backend/package.json
          action: rebuild