services:
  spotdl-frontend:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "5173:5173"  # Frontend
      - "3001:3001"  # Backend
    volumes:
      - ./downloads:/downloads  # Mount downloads directory
      - /home/tanc/mnt/media/music:/music  # Mount music directory
      - ./config:/app/backend/config  # Mount config directory
      - /app/node_modules  # Frontend node_modules volume
      - /app/backend/node_modules  # Backend node_modules volume
    environment:
      - NODE_ENV=production # Set NODE_ENV to development if needed
      - VITE_API_URL=http://localhost:3001  # Backend API URL
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./public
          target: /app/public
          action: sync
        - path: ./backend
          target: /app/backend
          action: sync
        - path: ./package.json
          action: rebuild
        - path: ./backend/package.json
          action: rebuild